### ISSUE TITLE
PUT /dmon/v1/overlord/applicaiton/ascvf returns status 500

### ISSUE THREAD

**Issue by tadeboro** [igabriel85/IeAT-DICE-Repository#155]
Stack trace, captured from Swagger interface:

```
Traceback (most recent call last):
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restplus/api.py", line 345, in handle_error
    return super(Api, self).handle_error(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restplus/api.py", line 345, in handle_error
    return super(Api, self).handle_error(e)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/IeAT-DICE-Repository/dmonEnv/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
TypeError: put() got an unexpected keyword argument 'appID'
```

**Comment by igabriel85** [comment]
Issue resolved
