### ISSUE TITLE
Error when starting v2 ES Core

### ISSUE THREAD

**Issue by igabriel85** [igabriel85/IeAT-DICE-Repository#159]
When starting ES Core using:
http://<IP>:5001/dmon/v2/overlord/core/es

Error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 345, in handle_error
    return super(Api, self).handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restplus/api.py", line 345, in handle_error
    return super(Api, self).handle_error(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/IeAT-DICE-Repository/src/pyDMON.py", line 2266, in post
    esPIDf = check_proc(pidESLoc)
  File "/opt/IeAT-DICE-Repository/src/pyUtil.py", line 709, in check_proc
    pid = int(stats_pid.read())
ValueError: invalid literal for int() with base 10: ''

**Comment by igabriel85** [comment]
Could be because of missing pidfile or pid in pidfile caused by non sudo permissions for dmon-controller. 

- enforce sudo for dmon or make dmon-es non sudo

**Comment by igabriel85** [comment]
fixed
