### ISSUE TITLE
Handle no metrics in defined timeframe

### ISSUE THREAD

**Issue by igabriel85** [igabriel85/IeAT-DICE-Repository#41]
Exception happened during processing of request from ('79.118.13.40', 58773)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 649, in __init__
    self.handle()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 200, in handle
    rv = BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 235, in handle_one_request
    return self.run_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 167, in execute
    for data in application_iter:
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/debug/**init**.py", line 88, in debug_application
    app_iter = self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 471, in wrapper
    resp = resource(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/**init**.py", line 581, in dispatch_request
    resp = meth(_args, *_kwargs)
  File "/opt/IeAT-DICE-Repository/src/pyDMON.py", line 340, in post
    dict2CSV(ListMetrics,request.json['DMON']['fname'])
  File "/opt/IeAT-DICE-Repository/src/pyESController.py", line 171, in dict2CSV
    sys.exit("listValues argument is empty. Please supply valid input!")
SystemExit: listValues argument is empty. Please supply valid input!

**Comment by igabriel85** [comment]
FIxed!
