### ISSUE TITLE
Must set FQDN of Monitoring VMs

### ISSUE THREAD

**Issue by igabriel85** [igabriel85/IeAT-DICE-Repository#88]
FQDN of host VMs must be set before local deployment and db population of data can occure.

Traceback (most recent call last):
  File "/opt/IeAT-DICE-Repository/src/start.py", line 171, in <module>
    main(sys.argv[1:])
  File "/opt/IeAT-DICE-Repository/src/start.py", line 118, in main
    corePopLS=dbSCore(hostFQDN=socket.getfqdn(),hostIP = socket.gethostbyname(socket.gethostname()),hostOS='ubuntu',
  File "/usr/local/lib/python2.7/dist-packages/gevent/socket.py", line 615, in gethostbyname
    return get_hub().resolver.gethostbyname(hostname)
  File "/usr/local/lib/python2.7/dist-packages/gevent/resolver_thread.py", line 28, in gethostbyname
    return self.pool.apply_e(self.expected_errors, _socket.gethostbyname, args)
  File "/usr/local/lib/python2.7/dist-packages/gevent/threadpool.py", line 225, in apply_e
    raise result
socket.gaierror: [Errno -2] Name or service not known
Exception KeyError: KeyError(140552818938256,) in <module 'threading' from '/usr/lib/python2.7/threading.pyc'> ignored

**Comment by igabriel85** [comment]
added capability to bootstrap script
